package com.samsung.cert_chain.mapper;

import com.samsung.cert_chain.model.Usrinfo;

import java.util.List;

public interface UsrinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usrinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usrinfo
     *
     * @mbg.generated
     */
    int insert(Usrinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usrinfo
     *
     * @mbg.generated
     */
    int insertSelective(Usrinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usrinfo
     *
     * @mbg.generated
     */
    Usrinfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usrinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Usrinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usrinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Usrinfo record);
    List<Usrinfo>  findAllUser();
}